spring:
  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: 'true'
  datasource:
    driverClassName: org.h2.Driver
    password: password
    username: sa
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: 'true'

server:
  port: '8085'

#Swagger Open Api `Configuration
info:
  contact:
    email: praveen369soni@gmail.com
    name: Praveen Soni
    url: https://github.com/praveen-soni-by/springboot-jpa-localdate-time.git
  description: Springboot with JPA and LocalDate Java8
  title: Book Service